
-- ── Mapping overrides (user feedback loop on canonicalization) ──
CREATE TABLE public.mapping_overrides (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  field_type    TEXT NOT NULL CHECK (field_type IN ('sponsor','indication','asset')),
  raw_value     TEXT NOT NULL,
  suggested_clean TEXT NOT NULL,
  note          TEXT,
  session_id    TEXT,
  vote_count    INTEGER NOT NULL DEFAULT 1,
  status        TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_mapping_overrides_lookup
  ON public.mapping_overrides(field_type, raw_value, status);

ALTER TABLE public.mapping_overrides ENABLE ROW LEVEL SECURITY;

CREATE POLICY "public read mapping_overrides"
  ON public.mapping_overrides FOR SELECT USING (true);
CREATE POLICY "public insert mapping_overrides"
  ON public.mapping_overrides FOR INSERT WITH CHECK (true);

CREATE TRIGGER trg_mapping_overrides_touch
  BEFORE UPDATE ON public.mapping_overrides
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

-- ── Broader sponsor seed (top 50ish) ──
INSERT INTO public.sponsor_mappings (raw_value, clean_value, mapping_type, confidence, source_note) VALUES
  ('AstraZeneca AB', 'AstraZeneca', 'rule', 99, 'Trim legal'),
  ('AstraZeneca PLC', 'AstraZeneca', 'rule', 99, 'Trim legal'),
  ('Hoffmann-La Roche', 'Roche', 'rule', 95, 'Trade name'),
  ('Roche Pharma AG', 'Roche', 'rule', 95, 'Subsidiary'),
  ('Genentech', 'Genentech (Roche)', 'rule', 90, 'Roche subsidiary'),
  ('Bayer', 'Bayer', 'rule', 99, 'Canonical'),
  ('Bayer AG', 'Bayer', 'rule', 99, 'Trim legal'),
  ('Bayer HealthCare', 'Bayer', 'rule', 95, 'Subsidiary'),
  ('Boehringer Ingelheim', 'Boehringer Ingelheim', 'rule', 99, 'Canonical'),
  ('Boehringer Ingelheim Pharmaceuticals', 'Boehringer Ingelheim', 'rule', 99, 'Subsidiary'),
  ('Takeda', 'Takeda', 'rule', 99, 'Canonical'),
  ('Takeda Pharmaceutical Company Limited', 'Takeda', 'rule', 99, 'Trim legal'),
  ('Takeda Pharmaceuticals U.S.A., Inc.', 'Takeda', 'rule', 95, 'US subsidiary'),
  ('AbbVie', 'AbbVie', 'rule', 99, 'Canonical'),
  ('AbbVie Inc.', 'AbbVie', 'rule', 99, 'Trim legal'),
  ('Amgen', 'Amgen', 'rule', 99, 'Canonical'),
  ('Amgen Inc.', 'Amgen', 'rule', 99, 'Trim legal'),
  ('Bristol-Myers Squibb Company', 'Bristol Myers Squibb', 'rule', 99, 'Drop hyphen + trim'),
  ('Bristol Myers Squibb', 'Bristol Myers Squibb', 'rule', 99, 'Canonical'),
  ('Celgene', 'Celgene (BMS)', 'rule', 90, 'BMS subsidiary'),
  ('Sanofi-Aventis', 'Sanofi', 'rule', 95, 'Trade name'),
  ('Sanofi U.S.', 'Sanofi', 'rule', 95, 'Subsidiary'),
  ('Regeneron Pharmaceuticals', 'Regeneron', 'rule', 99, 'Trim suffix'),
  ('Vertex Pharmaceuticals', 'Vertex', 'rule', 99, 'Trim suffix'),
  ('Vertex Pharmaceuticals Incorporated', 'Vertex', 'rule', 99, 'Trim legal'),
  ('Biogen', 'Biogen', 'rule', 99, 'Canonical'),
  ('Biogen Idec', 'Biogen', 'rule', 95, 'Legacy name'),
  ('Eisai', 'Eisai', 'rule', 99, 'Canonical'),
  ('Eisai Inc.', 'Eisai', 'rule', 99, 'Trim legal'),
  ('Eisai Co., Ltd.', 'Eisai', 'rule', 99, 'Trim legal'),
  ('Gilead Sciences', 'Gilead', 'rule', 99, 'Trim suffix'),
  ('Moderna', 'Moderna', 'rule', 99, 'Canonical'),
  ('ModernaTX, Inc.', 'Moderna', 'rule', 99, 'Trim legal'),
  ('BioNTech', 'BioNTech', 'rule', 99, 'Canonical'),
  ('BioNTech SE', 'BioNTech', 'rule', 99, 'Trim legal'),
  ('Daiichi Sankyo', 'Daiichi Sankyo', 'rule', 99, 'Canonical'),
  ('Daiichi Sankyo, Inc.', 'Daiichi Sankyo', 'rule', 99, 'Trim legal'),
  ('Daiichi Sankyo Co., Ltd.', 'Daiichi Sankyo', 'rule', 99, 'Trim legal'),
  ('Astellas Pharma Inc', 'Astellas', 'rule', 99, 'Trim suffix'),
  ('Astellas Pharma US, Inc.', 'Astellas', 'rule', 99, 'Trim legal'),
  ('Otsuka Pharmaceutical Co., Ltd.', 'Otsuka', 'rule', 99, 'Trim legal'),
  ('Otsuka Pharmaceutical Development & Commercialization, Inc.', 'Otsuka', 'rule', 95, 'Subsidiary'),
  ('Mitsubishi Tanabe Pharma', 'Mitsubishi Tanabe', 'rule', 95, 'Trim suffix'),
  ('UCB Pharma', 'UCB', 'rule', 95, 'Trim suffix'),
  ('UCB S.A.', 'UCB', 'rule', 99, 'Trim legal'),
  ('CSL Behring', 'CSL', 'rule', 90, 'Subsidiary'),
  ('Servier', 'Servier', 'rule', 99, 'Canonical'),
  ('Les Laboratoires Servier', 'Servier', 'rule', 95, 'French legal form'),
  ('Ipsen', 'Ipsen', 'rule', 99, 'Canonical'),
  ('Lundbeck', 'Lundbeck', 'rule', 99, 'Canonical'),
  ('H. Lundbeck A/S', 'Lundbeck', 'rule', 99, 'Trim legal'),
  ('Merck KGaA, Darmstadt, Germany', 'Merck KGaA', 'rule', 99, 'Distinguish from US Merck'),
  ('EMD Serono', 'Merck KGaA', 'rule', 90, 'US subsidiary of Merck KGaA'),
  ('National Cancer Institute (NCI)', 'NCI', 'rule', 99, 'Standard abbreviation'),
  ('National Cancer Institute', 'NCI', 'rule', 99, 'Standard abbreviation'),
  ('National Institute of Allergy and Infectious Diseases (NIAID)', 'NIAID', 'rule', 99, 'Standard abbreviation'),
  ('National Heart, Lung, and Blood Institute (NHLBI)', 'NHLBI', 'rule', 99, 'Standard abbreviation'),
  ('National Institute on Aging (NIA)', 'NIA', 'rule', 99, 'Standard abbreviation'),
  ('Memorial Sloan Kettering Cancer Center', 'MSKCC', 'rule', 95, 'Standard abbreviation'),
  ('M.D. Anderson Cancer Center', 'MD Anderson', 'rule', 95, 'Standard form'),
  ('Mayo Clinic', 'Mayo Clinic', 'rule', 99, 'Canonical'),
  ('Dana-Farber Cancer Institute', 'Dana-Farber', 'rule', 95, 'Trim suffix'),
  ('Massachusetts General Hospital', 'Mass General', 'rule', 95, 'Standard form')
ON CONFLICT (raw_value) DO NOTHING;

-- ── Broader indication seed ──
INSERT INTO public.indication_mappings (raw_value, clean_value, mapping_type, confidence, source_note) VALUES
  ('Lung Cancer', 'Lung cancer', 'rule', 99, 'Case standard'),
  ('Small Cell Lung Cancer', 'SCLC', 'rule', 99, 'Standard abbreviation'),
  ('Carcinoma, Small-Cell Lung', 'SCLC', 'rule', 99, 'MeSH form'),
  ('Lung Adenocarcinoma', 'NSCLC (adenocarcinoma)', 'rule', 95, 'NSCLC subtype'),
  ('Squamous Cell Lung Carcinoma', 'NSCLC (squamous)', 'rule', 95, 'NSCLC subtype'),
  ('Breast Cancer', 'Breast cancer', 'rule', 99, 'Case standard'),
  ('Triple Negative Breast Cancer', 'TNBC', 'rule', 99, 'Standard abbreviation'),
  ('HER2-positive Breast Cancer', 'HER2+ breast cancer', 'rule', 95, 'Standard form'),
  ('Metastatic Breast Cancer', 'mBC', 'rule', 90, 'Standard abbreviation'),
  ('Colorectal Neoplasms', 'Colorectal cancer', 'rule', 95, 'MeSH → plain'),
  ('Colorectal Cancer', 'Colorectal cancer', 'rule', 99, 'Canonical'),
  ('Prostatic Neoplasms', 'Prostate cancer', 'rule', 95, 'MeSH → plain'),
  ('Prostate Cancer', 'Prostate cancer', 'rule', 99, 'Canonical'),
  ('Pancreatic Neoplasms', 'Pancreatic cancer', 'rule', 95, 'MeSH → plain'),
  ('Ovarian Neoplasms', 'Ovarian cancer', 'rule', 95, 'MeSH → plain'),
  ('Multiple Myeloma', 'Multiple myeloma', 'rule', 99, 'Case standard'),
  ('Acute Myeloid Leukemia', 'AML', 'rule', 99, 'Standard abbreviation'),
  ('Acute Lymphoblastic Leukemia', 'ALL', 'rule', 99, 'Standard abbreviation'),
  ('Chronic Lymphocytic Leukemia', 'CLL', 'rule', 99, 'Standard abbreviation'),
  ('Chronic Myeloid Leukemia', 'CML', 'rule', 99, 'Standard abbreviation'),
  ('Diffuse Large B-Cell Lymphoma', 'DLBCL', 'rule', 99, 'Standard abbreviation'),
  ('Hodgkin Disease', 'Hodgkin lymphoma', 'rule', 95, 'MeSH → plain'),
  ('Non-Hodgkin Lymphoma', 'NHL', 'rule', 99, 'Standard abbreviation'),
  ('Glioblastoma', 'Glioblastoma', 'rule', 99, 'Canonical'),
  ('Hepatocellular Carcinoma', 'HCC', 'rule', 99, 'Standard abbreviation'),
  ('Renal Cell Carcinoma', 'RCC', 'rule', 99, 'Standard abbreviation'),
  ('Melanoma', 'Melanoma', 'rule', 99, 'Canonical'),
  ('Parkinson Disease', 'Parkinson''s disease', 'rule', 95, 'Possessive standard'),
  ('Parkinson''s Disease', 'Parkinson''s disease', 'rule', 99, 'Canonical'),
  ('Multiple Sclerosis', 'Multiple sclerosis', 'rule', 99, 'Case standard'),
  ('Amyotrophic Lateral Sclerosis', 'ALS', 'rule', 99, 'Standard abbreviation'),
  ('Huntington Disease', 'Huntington''s disease', 'rule', 95, 'Possessive standard'),
  ('Epilepsy', 'Epilepsy', 'rule', 99, 'Canonical'),
  ('Migraine Disorders', 'Migraine', 'rule', 95, 'MeSH → plain'),
  ('Major Depressive Disorder', 'MDD', 'rule', 99, 'Standard abbreviation'),
  ('Schizophrenia', 'Schizophrenia', 'rule', 99, 'Canonical'),
  ('Bipolar Disorder', 'Bipolar disorder', 'rule', 99, 'Case standard'),
  ('Anxiety Disorders', 'Anxiety disorder', 'rule', 95, 'Singular form'),
  ('Diabetes Mellitus, Type 1', 'Type 1 diabetes', 'rule', 99, 'MeSH form'),
  ('Type 1 Diabetes Mellitus', 'Type 1 diabetes', 'rule', 99, 'Drop "mellitus"'),
  ('Heart Failure', 'Heart failure', 'rule', 99, 'Case standard'),
  ('Heart Failure, Systolic', 'HFrEF', 'rule', 95, 'Standard abbreviation'),
  ('Heart Failure with Preserved Ejection Fraction', 'HFpEF', 'rule', 99, 'Standard abbreviation'),
  ('Atrial Fibrillation', 'Atrial fibrillation', 'rule', 99, 'Case standard'),
  ('Hypertension', 'Hypertension', 'rule', 99, 'Canonical'),
  ('Coronary Artery Disease', 'CAD', 'rule', 99, 'Standard abbreviation'),
  ('Myocardial Infarction', 'Myocardial infarction', 'rule', 99, 'Case standard'),
  ('Stroke', 'Stroke', 'rule', 99, 'Canonical'),
  ('Asthma', 'Asthma', 'rule', 99, 'Canonical'),
  ('Pulmonary Disease, Chronic Obstructive', 'COPD', 'rule', 99, 'MeSH → abbrev'),
  ('Chronic Obstructive Pulmonary Disease', 'COPD', 'rule', 99, 'Standard abbreviation'),
  ('Idiopathic Pulmonary Fibrosis', 'IPF', 'rule', 99, 'Standard abbreviation'),
  ('Cystic Fibrosis', 'Cystic fibrosis', 'rule', 99, 'Case standard'),
  ('Rheumatoid Arthritis', 'Rheumatoid arthritis', 'rule', 99, 'Case standard'),
  ('Psoriasis', 'Psoriasis', 'rule', 99, 'Canonical'),
  ('Psoriatic Arthritis', 'Psoriatic arthritis', 'rule', 99, 'Case standard'),
  ('Inflammatory Bowel Diseases', 'IBD', 'rule', 95, 'Standard abbreviation'),
  ('Crohn Disease', 'Crohn''s disease', 'rule', 95, 'Possessive standard'),
  ('Ulcerative Colitis', 'Ulcerative colitis', 'rule', 99, 'Case standard'),
  ('Lupus Erythematosus, Systemic', 'SLE', 'rule', 99, 'MeSH → abbrev'),
  ('Atopic Dermatitis', 'Atopic dermatitis', 'rule', 99, 'Case standard'),
  ('Chronic Kidney Diseases', 'CKD', 'rule', 95, 'Standard abbreviation'),
  ('Non-alcoholic Fatty Liver Disease', 'NAFLD', 'rule', 99, 'Standard abbreviation'),
  ('Nonalcoholic Steatohepatitis', 'NASH', 'rule', 99, 'Standard abbreviation'),
  ('HIV Infections', 'HIV', 'rule', 95, 'MeSH → abbrev'),
  ('Hepatitis C', 'Hepatitis C', 'rule', 99, 'Canonical'),
  ('Hepatitis B', 'Hepatitis B', 'rule', 99, 'Canonical'),
  ('COVID-19', 'COVID-19', 'rule', 99, 'Canonical'),
  ('SARS-CoV-2 Infection', 'COVID-19', 'rule', 95, 'Standard form'),
  ('Sickle Cell Disease', 'Sickle cell disease', 'rule', 99, 'Case standard'),
  ('Spinal Muscular Atrophy', 'SMA', 'rule', 99, 'Standard abbreviation'),
  ('Duchenne Muscular Dystrophy', 'DMD', 'rule', 99, 'Standard abbreviation')
ON CONFLICT (raw_value) DO NOTHING;

-- ── Broader asset seed ──
INSERT INTO public.asset_mappings (raw_value, clean_value, mapping_type, confidence, source_note) VALUES
  ('Dulaglutide', 'Dulaglutide (GLP-1)', 'rule', 95, 'GLP-1 agonist'),
  ('Exenatide', 'Exenatide (GLP-1)', 'rule', 95, 'GLP-1 agonist'),
  ('Cemiplimab', 'Cemiplimab (anti-PD-1)', 'rule', 95, 'Checkpoint class'),
  ('Avelumab', 'Avelumab (anti-PD-L1)', 'rule', 95, 'Checkpoint class'),
  ('Ipilimumab', 'Ipilimumab (anti-CTLA-4)', 'rule', 95, 'Checkpoint class'),
  ('Tremelimumab', 'Tremelimumab (anti-CTLA-4)', 'rule', 95, 'Checkpoint class'),
  ('Trastuzumab', 'Trastuzumab (anti-HER2)', 'rule', 95, 'Targeted therapy'),
  ('Pertuzumab', 'Pertuzumab (anti-HER2)', 'rule', 95, 'Targeted therapy'),
  ('Ado-trastuzumab emtansine', 'T-DM1 (anti-HER2 ADC)', 'rule', 90, 'ADC class'),
  ('Trastuzumab deruxtecan', 'T-DXd (anti-HER2 ADC)', 'rule', 90, 'ADC class'),
  ('Sacituzumab govitecan', 'Sacituzumab govitecan (anti-Trop-2 ADC)', 'rule', 90, 'ADC class'),
  ('Rituximab', 'Rituximab (anti-CD20)', 'rule', 95, 'Targeted therapy'),
  ('Obinutuzumab', 'Obinutuzumab (anti-CD20)', 'rule', 95, 'Targeted therapy'),
  ('Bevacizumab', 'Bevacizumab (anti-VEGF)', 'rule', 95, 'Targeted therapy'),
  ('Ibrutinib', 'Ibrutinib (BTK inhibitor)', 'rule', 95, 'BTKi class'),
  ('Acalabrutinib', 'Acalabrutinib (BTK inhibitor)', 'rule', 95, 'BTKi class'),
  ('Zanubrutinib', 'Zanubrutinib (BTK inhibitor)', 'rule', 95, 'BTKi class'),
  ('Tofacitinib', 'Tofacitinib (JAK inhibitor)', 'rule', 95, 'JAKi class'),
  ('Baricitinib', 'Baricitinib (JAK inhibitor)', 'rule', 95, 'JAKi class'),
  ('Upadacitinib', 'Upadacitinib (JAK inhibitor)', 'rule', 95, 'JAKi class'),
  ('Empagliflozin', 'Empagliflozin (SGLT2)', 'rule', 95, 'SGLT2 class'),
  ('Dapagliflozin', 'Dapagliflozin (SGLT2)', 'rule', 95, 'SGLT2 class'),
  ('Canagliflozin', 'Canagliflozin (SGLT2)', 'rule', 95, 'SGLT2 class'),
  ('Sitagliptin', 'Sitagliptin (DPP-4)', 'rule', 95, 'DPP-4 class'),
  ('Linagliptin', 'Linagliptin (DPP-4)', 'rule', 95, 'DPP-4 class'),
  ('Evolocumab', 'Evolocumab (PCSK9)', 'rule', 95, 'PCSK9 class'),
  ('Alirocumab', 'Alirocumab (PCSK9)', 'rule', 95, 'PCSK9 class'),
  ('Inclisiran', 'Inclisiran (PCSK9 siRNA)', 'rule', 95, 'PCSK9 siRNA'),
  ('Erenumab', 'Erenumab (anti-CGRP)', 'rule', 95, 'Migraine class'),
  ('Galcanezumab', 'Galcanezumab (anti-CGRP)', 'rule', 95, 'Migraine class'),
  ('Fremanezumab', 'Fremanezumab (anti-CGRP)', 'rule', 95, 'Migraine class'),
  ('Eptinezumab', 'Eptinezumab (anti-CGRP)', 'rule', 95, 'Migraine class'),
  ('Adalimumab', 'Adalimumab (anti-TNF)', 'rule', 95, 'Anti-TNF class'),
  ('Etanercept', 'Etanercept (anti-TNF)', 'rule', 95, 'Anti-TNF class'),
  ('Infliximab', 'Infliximab (anti-TNF)', 'rule', 95, 'Anti-TNF class'),
  ('Ustekinumab', 'Ustekinumab (anti-IL-12/23)', 'rule', 95, 'IL-12/23 class'),
  ('Secukinumab', 'Secukinumab (anti-IL-17A)', 'rule', 95, 'IL-17 class'),
  ('Ixekizumab', 'Ixekizumab (anti-IL-17A)', 'rule', 95, 'IL-17 class'),
  ('Risankizumab', 'Risankizumab (anti-IL-23)', 'rule', 95, 'IL-23 class'),
  ('Guselkumab', 'Guselkumab (anti-IL-23)', 'rule', 95, 'IL-23 class'),
  ('Dupilumab', 'Dupilumab (anti-IL-4Ra)', 'rule', 95, 'Type 2 inflammation'),
  ('Omalizumab', 'Omalizumab (anti-IgE)', 'rule', 95, 'Asthma class'),
  ('Mepolizumab', 'Mepolizumab (anti-IL-5)', 'rule', 95, 'Asthma class'),
  ('Benralizumab', 'Benralizumab (anti-IL-5R)', 'rule', 95, 'Asthma class'),
  ('Osimertinib', 'Osimertinib (EGFR TKI)', 'rule', 95, 'EGFR class'),
  ('Erlotinib', 'Erlotinib (EGFR TKI)', 'rule', 95, 'EGFR class'),
  ('Gefitinib', 'Gefitinib (EGFR TKI)', 'rule', 95, 'EGFR class'),
  ('Sotorasib', 'Sotorasib (KRAS G12C)', 'rule', 95, 'KRAS class'),
  ('Adagrasib', 'Adagrasib (KRAS G12C)', 'rule', 95, 'KRAS class'),
  ('Olaparib', 'Olaparib (PARP)', 'rule', 95, 'PARP class'),
  ('Niraparib', 'Niraparib (PARP)', 'rule', 95, 'PARP class'),
  ('Talazoparib', 'Talazoparib (PARP)', 'rule', 95, 'PARP class'),
  ('Enzalutamide', 'Enzalutamide (AR antagonist)', 'rule', 95, 'AR class'),
  ('Abiraterone', 'Abiraterone (CYP17 inhibitor)', 'rule', 95, 'AR axis'),
  ('Apalutamide', 'Apalutamide (AR antagonist)', 'rule', 95, 'AR class'),
  ('Venetoclax', 'Venetoclax (BCL-2)', 'rule', 95, 'BCL-2 class'),
  ('Ivosidenib', 'Ivosidenib (IDH1)', 'rule', 95, 'IDH class'),
  ('Enasidenib', 'Enasidenib (IDH2)', 'rule', 95, 'IDH class'),
  ('Tisagenlecleucel', 'Tisagenlecleucel (CD19 CAR-T)', 'rule', 95, 'Cell therapy'),
  ('Axicabtagene ciloleucel', 'Axi-cel (CD19 CAR-T)', 'rule', 95, 'Cell therapy'),
  ('Lisocabtagene maraleucel', 'Liso-cel (CD19 CAR-T)', 'rule', 95, 'Cell therapy'),
  ('Idecabtagene vicleucel', 'Ide-cel (BCMA CAR-T)', 'rule', 95, 'Cell therapy')
ON CONFLICT (raw_value) DO NOTHING;
